/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Change request type by appending new active version
 */
export interface ChangeTypeRequest {
  name: string;
  description?: string;
  payloadHandlerId: string;
  processDefinitionKey: string;
}
