/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CompleteTaskRequestAction } from './completeTaskRequestAction';

/**
 * Request payload for completing a workflow user task
 */
export interface CompleteTaskRequest {
  /** Task action */
  action: CompleteTaskRequestAction;
  /** Task completion comment */
  comment?: string;
}
