/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Task action
 */
export type CompleteTaskRequestAction = typeof CompleteTaskRequestAction[keyof typeof CompleteTaskRequestAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompleteTaskRequestAction = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;
