/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateRequestPayload } from './createRequestPayload';

/**
 * Request payload for creating and submitting a new request
 */
export interface CreateRequest {
  /** Request type key */
  requestTypeKey: string;
  /** Request payload */
  payload: CreateRequestPayload;
}
