/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Validation error details
 */
export type CreateEsignEmbeddedView409ErrorsItem = {
  /** Name of the invalid field */
  name?: string;
  /** Validation error code */
  code?: string;
  /** Reason for the validation failure */
  message?: string;
};
