/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Request payload
 */
export type CreateRequestPayload = { [key: string]: unknown };
