/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateDraft400ErrorsItem } from './createDraft400ErrorsItem';

export type CreateDraft400 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: CreateDraft400ErrorsItem[];
};
