/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { IdempotencyKeyParameter } from './idempotencyKeyParameter';

export type Create3Headers = {
/**
 * Unique key to ensure request idempotency
 */
'Idempotency-Key': IdempotencyKeyParameter;
};
