/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Create request type with initial active version
 */
export interface CreateTypeRequest {
  typeKey: string;
  name: string;
  description?: string;
  payloadHandlerId: string;
  processDefinitionKey: string;
}
