/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Response containing the ID of a newly created resource
 */
export interface CreateResponse {
  /** Unique identifier of the created resource */
  id?: number;
}
