/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateEsignEnvelope400ErrorsItem } from './createEsignEnvelope400ErrorsItem';

export type CreateEsignEnvelope400 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: CreateEsignEnvelope400ErrorsItem[];
};
