/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Create user request
 */
export interface CreateUserRequest {
  username: string;
  email: string;
  active?: boolean;
  tenantId?: number;
}
