/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EsignCreateEnvelopeRequest } from './esignCreateEnvelopeRequest';

export type CreateEsignEnvelopeBody = {
  file: Blob;
  request: EsignCreateEnvelopeRequest;
};
