/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateEsignEmbeddedView409ErrorsItem } from './createEsignEmbeddedView409ErrorsItem';

export type CreateEsignEmbeddedView409 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: CreateEsignEmbeddedView409ErrorsItem[];
};
