/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Delete3400ErrorsItem } from './delete3400ErrorsItem';

export type Delete3400 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: Delete3400ErrorsItem[];
};
