/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DocumentTemplateFormField } from './documentTemplateFormField';

/**
 * Parsed form map for a document template
 */
export interface DocumentTemplateFormMap {
  /** Discovered template fields */
  fields?: DocumentTemplateFormField[];
}
