/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GenerateInput } from './generateInput';

/**
 * Generate command for composing merged output from document templates
 */
export interface DocumentTemplateGenerateRequest {
  /** Ordered template inputs to render and merge */
  documents: GenerateInput[];
}
