/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Parsed e-sign anchor metadata
 */
export interface DocumentTemplateEsignAnchorMetadata {
  /** Discovered signature anchor keys */
  signatureAnchorKeys?: string[];
  /** Discovered date-signed anchor keys */
  dateAnchorKeys?: string[];
  esignable?: boolean;
}
