/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Multipart request metadata for updating a document template
 */
export interface DocumentTemplateUpdateRequest {
  /** Optional English template name */
  enName?: string;
  /** Optional French template name */
  frName?: string;
  /** Optional English description */
  enDescription?: string;
  /** Optional French description */
  frDescription?: string;
}
