/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DocumentTemplateResponseLanguage } from './documentTemplateResponseLanguage';
import type { DocumentTemplateFormMap } from './documentTemplateFormMap';
import type { DocumentTemplateEsignAnchorMetadata } from './documentTemplateEsignAnchorMetadata';

/**
 * Response representing document-template metadata
 */
export interface DocumentTemplateResponse {
  /** Unique identifier of the file */
  id?: number;
  /** English display name for the file */
  enName?: string;
  /** French display name for the file */
  frName?: string;
  /** Optional English user-provided description */
  enDescription?: string;
  /** Optional French user-provided description */
  frDescription?: string;
  /** MIME type */
  mimeType?: string;
  /** Stored file size in bytes */
  contentSize?: number;
  /** SHA-256 checksum of uploaded content */
  checksumSha256?: string;
  /** Document template language */
  language?: DocumentTemplateResponseLanguage;
  /** Optional tenant identifier. Null indicates a global template */
  tenantId?: number;
  /** Parsed form map with fields, field types, and possible values for selectable controls */
  formMap?: DocumentTemplateFormMap;
  /** Parsed e-sign anchor metadata */
  esignAnchorMetadata?: DocumentTemplateEsignAnchorMetadata;
  /** Whether this template includes configured e-signature anchors */
  esignable?: boolean;
  /** Timestamp when this record was created */
  createdAt?: string;
  /** Timestamp when this record was last updated */
  updatedAt?: string;
  /** Optimistic-lock version */
  version?: number;
}
