/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Document template language
 */
export type DocumentTemplateResponseLanguage = typeof DocumentTemplateResponseLanguage[keyof typeof DocumentTemplateResponseLanguage];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentTemplateResponseLanguage = {
  ENGLISH: 'ENGLISH',
  FRENCH: 'FRENCH',
} as const;
