/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DocumentTemplateUploadRequestLanguage } from './documentTemplateUploadRequestLanguage';

/**
 * Multipart request metadata for uploading a document template
 */
export interface DocumentTemplateUploadRequest {
  /** English template name */
  enName: string;
  /** Optional French template name */
  frName?: string;
  /** Optional English description */
  enDescription?: string;
  /** Optional French description */
  frDescription?: string;
  /** Template language */
  language: DocumentTemplateUploadRequestLanguage;
  /** Optional tenant scope */
  tenantId?: number;
}
