/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Template language
 */
export type DocumentTemplateUploadRequestLanguage = typeof DocumentTemplateUploadRequestLanguage[keyof typeof DocumentTemplateUploadRequestLanguage];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentTemplateUploadRequestLanguage = {
  ENGLISH: 'ENGLISH',
  FRENCH: 'FRENCH',
} as const;
