/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DownloadEsignSignedDocument409ErrorsItem } from './downloadEsignSignedDocument409ErrorsItem';

export type DownloadEsignSignedDocument409 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: DownloadEsignSignedDocument409ErrorsItem[];
};
