/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DownloadEsignCertificate409ErrorsItem } from './downloadEsignCertificate409ErrorsItem';

export type DownloadEsignCertificate409 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: DownloadEsignCertificate409ErrorsItem[];
};
