/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EsignSignerResponseDeliveryMethod } from './esignSignerResponseDeliveryMethod';
import type { EsignSignerResponseAuthMethod } from './esignSignerResponseAuthMethod';
import type { EsignSignerResponseStatus } from './esignSignerResponseStatus';

/**
 * Current signer state
 */
export interface EsignSignerResponse {
  /** Anchor role key */
  roleKey?: string;
  /** Signature anchor text embedded in the PDF */
  signatureAnchorText?: string;
  /** Date-signed anchor text embedded in the PDF */
  dateAnchorText?: string;
  /** Routing order */
  routingOrder?: number;
  /** Signer full name */
  fullName?: string;
  /** Signer email address */
  email?: string;
  /** Signer delivery method */
  deliveryMethod?: EsignSignerResponseDeliveryMethod;
  /** Signer authentication method */
  authMethod?: EsignSignerResponseAuthMethod;
  /** Provider recipient id */
  providerRecipientId?: string;
  /** Current signer status */
  status?: EsignSignerResponseStatus;
  /** Timestamp when the signer viewed the envelope */
  viewedAt?: string;
  /** Timestamp when the signer completed signing */
  completedAt?: string;
  /** Timestamp of the most recent provider status update */
  lastStatusAt?: string;
}
