/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EsignEnvelopeResponseDeliveryMode } from './esignEnvelopeResponseDeliveryMode';
import type { EsignEnvelopeResponseStatus } from './esignEnvelopeResponseStatus';
import type { EsignSignerResponse } from './esignSignerResponse';

/**
 * Current envelope state including signer details
 */
export interface EsignEnvelopeResponse {
  /** Internal envelope id */
  id?: number;
  /** Provider envelope id */
  externalEnvelopeId?: string;
  /** Envelope subject */
  subject?: string;
  /** Envelope message */
  message?: string;
  /** Source file name */
  fileName?: string;
  /** Envelope delivery mode */
  deliveryMode?: EsignEnvelopeResponseDeliveryMode;
  /** Current envelope status */
  status?: EsignEnvelopeResponseStatus;
  /** Optional tenant id */
  tenantId?: number;
  /** Whether reminders are enabled */
  remindersEnabled?: boolean;
  /** Configured reminder interval in hours */
  reminderIntervalHours?: number;
  /** Reason provided when the envelope was voided */
  voidedReason?: string;
  /** Completion timestamp when fully signed */
  completedAt?: string;
  /** Last provider update timestamp */
  lastProviderUpdateAt?: string;
  /** Whether the signing certificate can be downloaded */
  certificateReady?: boolean;
  /** Whether the completed signed PDF can be downloaded */
  signedDocumentReady?: boolean;
  /** Signer states in routing order */
  signers?: EsignSignerResponse[];
  /** Created timestamp */
  createdAt?: string;
  /** Updated timestamp */
  updatedAt?: string;
}
