/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Signer delivery method
 */
export type EsignSignerResponseDeliveryMethod = typeof EsignSignerResponseDeliveryMethod[keyof typeof EsignSignerResponseDeliveryMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EsignSignerResponseDeliveryMethod = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
} as const;
