/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Current signer status
 */
export type EsignSignerResponseStatus = typeof EsignSignerResponseStatus[keyof typeof EsignSignerResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EsignSignerResponseStatus = {
  CREATED: 'CREATED',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  DECLINED: 'DECLINED',
  VOIDED: 'VOIDED',
} as const;
