/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Whether the envelope is in-person or remote
 */
export type EsignCreateEnvelopeRequestDeliveryMode = typeof EsignCreateEnvelopeRequestDeliveryMode[keyof typeof EsignCreateEnvelopeRequestDeliveryMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EsignCreateEnvelopeRequestDeliveryMode = {
  IN_PERSON: 'IN_PERSON',
  REMOTE: 'REMOTE',
} as const;
