/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EsignCreateEnvelopeRequestDeliveryMode } from './esignCreateEnvelopeRequestDeliveryMode';
import type { SignerInput } from './signerInput';

/**
 * Create-envelope request submitted with the source PDF upload
 */
export interface EsignCreateEnvelopeRequest {
  /** Email subject shown to remote signers */
  subject: string;
  /** Optional message shown to signers */
  message?: string;
  /** Whether the envelope is in-person or remote */
  deliveryMode: EsignCreateEnvelopeRequestDeliveryMode;
  /** Whether automated reminders are enabled for remote signing */
  remindersEnabled?: boolean;
  /** Reminder interval in hours when reminders are enabled */
  reminderIntervalHours?: number;
  /** Ordered signer definitions mapped to PDF anchors */
  signers: SignerInput[];
}
