/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Void-envelope request
 */
export interface EsignVoidRequest {
  /** Reason recorded against the voided envelope */
  reason: string;
}
