/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Envelope delivery mode
 */
export type EsignEnvelopeResponseDeliveryMode = typeof EsignEnvelopeResponseDeliveryMode[keyof typeof EsignEnvelopeResponseDeliveryMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EsignEnvelopeResponseDeliveryMode = {
  IN_PERSON: 'IN_PERSON',
  REMOTE: 'REMOTE',
} as const;
