/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Ephemeral embedded signing view URL
 */
export interface EsignEmbeddedViewResponse {
  /** Signer role key */
  roleKey?: string;
  /** Fresh DocuSign embedded signing URL */
  signingUrl?: string;
}
