/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Current envelope status
 */
export type EsignEnvelopeResponseStatus = typeof EsignEnvelopeResponseStatus[keyof typeof EsignEnvelopeResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EsignEnvelopeResponseStatus = {
  CREATED: 'CREATED',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  DECLINED: 'DECLINED',
  COMPLETED: 'COMPLETED',
  VOIDED: 'VOIDED',
} as const;
