/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Summary response for an ad hoc e-sign envelope reconciliation run
 */
export interface EsignReconcileResponse {
  /** Number of active local envelopes considered for reconciliation */
  activeEnvelopeCount?: number;
  /** Number of envelopes returned by the provider for the requested batch */
  providerEnvelopeCount?: number;
  /** Number of local envelopes updated during reconciliation */
  reconciledEnvelopeCount?: number;
  /** Internal ids of envelopes whose local state changed */
  reconciledEnvelopeIds?: number[];
}
