/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Signer authentication method
 */
export type EsignSignerResponseAuthMethod = typeof EsignSignerResponseAuthMethod[keyof typeof EsignSignerResponseAuthMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EsignSignerResponseAuthMethod = {
  NONE: 'NONE',
  PASSCODE: 'PASSCODE',
  SMS: 'SMS',
} as const;
