/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Field map used for PDF form fill or Word placeholder merge
 */
export type GenerateInputFields = {[key: string]: { [key: string]: unknown }};
