/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GenerateInputFields } from './generateInputFields';

/**
 * One template render instruction
 */
export interface GenerateInput {
  /** Template identifier */
  documentTemplateId: number;
  /** Field map used for PDF form fill or Word placeholder merge */
  fields?: GenerateInputFields;
}
