/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GenerateDocumentTemplate400ErrorsItem } from './generateDocumentTemplate400ErrorsItem';

export type GenerateDocumentTemplate400 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: GenerateDocumentTemplate400ErrorsItem[];
};
