/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Unique key to ensure request idempotency
 */
export type IdempotencyKeyParameter = string;
