/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ModelerInputField } from './modelerInputField';

/**
 * Grouped input universe for the modeler
 */
export interface Inputs {
  /** Payload fields inferred from the request payload contract */
  payloadFields?: ModelerInputField[];
  /** Computed fields derived from provider bundles */
  computedFields?: ModelerInputField[];
  /** Workflow/runtime fields available for branching */
  workflowFields?: ModelerInputField[];
}
