/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ModelerInputFieldType } from './modelerInputFieldType';
import type { ModelerInputFieldExamplesItem } from './modelerInputFieldExamplesItem';

/**
 * Modeler input field descriptor
 */
export interface ModelerInputField {
  /** Stable field key */
  key?: string;
  /** Human-readable field label */
  label?: string;
  /** Field data type */
  type?: ModelerInputFieldType;
  /** Whether field is required */
  required?: boolean;
  /** JSONPath for payload fields */
  path?: string;
  /** Provider key for computed/workflow fields */
  providerKey?: string;
  /** Dependency keys for computed/workflow fields */
  dependsOn?: string[];
  /** Allowed enum values where applicable */
  enumValues?: string[];
  /** Example values for authoring hints */
  examples?: ModelerInputFieldExamplesItem[];
  /** Field description shown in the modeler */
  description?: string;
}
