/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Field data type
 */
export type ModelerInputFieldType = typeof ModelerInputFieldType[keyof typeof ModelerInputFieldType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelerInputFieldType = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  BOOLEAN: 'BOOLEAN',
  DATE: 'DATE',
  DATETIME: 'DATETIME',
  JSON: 'JSON',
} as const;
