/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RequestTypeSearchResponse } from './requestTypeSearchResponse';

/**
 * A generic response wrapper for paginated search results
 */
export interface PagedResponseRequestTypeSearchResponse {
  /** The list of results for the current page */
  items?: RequestTypeSearchResponse[];
  /** Total number of matching records across all pages */
  totalElements?: number;
  /** Zero-indexed current page number */
  page?: number;
  /** Number of records per page */
  size?: number;
  /** Total number of pages */
  totalPages?: number;
}
