/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Reason code option
 */
export interface ReasonCodeOption {
  /** Stable reason code value */
  code?: string;
  /** Human-readable reason code label */
  label?: string;
}
