/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RequestResponseStatus } from './requestResponseStatus';
import type { RequestResponsePayload } from './requestResponsePayload';
import type { RequestTaskResponse } from './requestTaskResponse';

/**
 * Response representing a request record
 */
export interface RequestResponse {
  /** Unique identifier of the request */
  id?: number;
  /** Request type key used for this request */
  requestTypeKey?: string;
  /** Resolved immutable request type version */
  requestTypeVersion?: number;
  /** Current status of the request */
  status?: RequestResponseStatus;
  /** Payload data */
  payload?: RequestResponsePayload;
  /** Timestamp when the request was created */
  createdAt?: string;
  /** Timestamp when the request was last updated */
  updatedAt?: string;
  /** Version of the record for optimistic locking */
  version?: number;
  /** Workflow user tasks linked to this request */
  userTasks?: RequestTaskResponse[];
}
