/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RequestSearchResponseStatus } from './requestSearchResponseStatus';

/**
 * Summary response representing a request in search results
 */
export interface RequestSearchResponse {
  /** Unique identifier of the request */
  id?: number;
  /** Request type key used for this request */
  requestTypeKey?: string;
  /** Resolved immutable request type version */
  requestTypeVersion?: number;
  /** Current status of the request */
  status?: RequestSearchResponseStatus;
  /** Timestamp when the request was created */
  createdAt?: string;
  /** Timestamp when the request was last updated */
  updatedAt?: string;
  /** Version of the record for optimistic locking */
  version?: number;
}
