/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type RequestTypeModelerCapabilitiesResponseAvailableEscalationHandlersItem = typeof RequestTypeModelerCapabilitiesResponseAvailableEscalationHandlersItem[keyof typeof RequestTypeModelerCapabilitiesResponseAvailableEscalationHandlersItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestTypeModelerCapabilitiesResponseAvailableEscalationHandlersItem = {
  OPS_REROUTE: 'OPS_REROUTE',
  SLA_BREACH_MANAGER_ESCALATION: 'SLA_BREACH_MANAGER_ESCALATION',
  NOTIFY_REQUEST_OWNER: 'NOTIFY_REQUEST_OWNER',
} as const;
