/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Request type summary with current active version mapping
 */
export interface RequestTypeSearchResponse {
  /** Stable type key */
  typeKey?: string;
  /** Display name */
  name?: string;
  /** Description */
  description?: string;
  /** Whether the type is active */
  active?: boolean;
  /** Current active immutable version */
  activeVersion?: number;
  /** Payload handler id for active version */
  payloadHandlerId?: string;
  /** Process definition key for active version */
  processDefinitionKey?: string;
}
