/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Current status of the request
 */
export type RequestResponseStatus = typeof RequestResponseStatus[keyof typeof RequestResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestResponseStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_SIGNATURE: 'AWAITING_SIGNATURE',
  AWAITING_PROCESSING: 'AWAITING_PROCESSING',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
} as const;
