/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type RequestActivitySearchCriteriaEventTypesItem = typeof RequestActivitySearchCriteriaEventTypesItem[keyof typeof RequestActivitySearchCriteriaEventTypesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestActivitySearchCriteriaEventTypesItem = {
  STATUS_CHANGED: 'STATUS_CHANGED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_COMPLETED: 'TASK_COMPLETED',
} as const;
