/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RequestStatusChangedActivityPayload } from './requestStatusChangedActivityPayload';
import type { RequestTaskAssignedActivityPayload } from './requestTaskAssignedActivityPayload';
import type { RequestTaskCompletedActivityPayload } from './requestTaskCompletedActivityPayload';

/**
 * Typed request activity payload
 */
export type RequestActivityPayload = RequestStatusChangedActivityPayload | RequestTaskAssignedActivityPayload | RequestTaskCompletedActivityPayload;
