/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RequestSearchCriteriaStatusesItem } from './requestSearchCriteriaStatusesItem';

/**
 * Criteria for searching request records
 */
export interface RequestSearchCriteria {
  /**
   * Zero-indexed page number
   * @minimum 0
   */
  page?: number;
  /**
   * Number of records per page
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** Partial request type key to search for (case-insensitive) */
  nameContains?: string;
  /** Request type keys filter */
  requestTypeKeys?: string[];
  /** List of statuses to filter by */
  statuses?: RequestSearchCriteriaStatusesItem[];
  /** List of specific IDs to filter by */
  ids?: number[];
  /** Task assignee filter */
  taskAssignee?: string;
  /** Task assignees filter */
  taskAssignees?: string[];
  namePattern?: string;
  normalizedRequestTypeKeys?: string[];
  normalizedTaskAssignees?: string[];
}
