/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Criteria for searching request types
 */
export interface RequestTypeSearchCriteria {
  /**
   * Zero-indexed page number
   * @minimum 0
   */
  page?: number;
  /**
   * Number of records per page
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** Case-insensitive substring filter for type key */
  typeKeyContains?: string;
  /** Filter by active flag */
  active?: boolean;
  typeKeyPattern?: string;
}
