/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RequestActivityEventResponseEventType } from './requestActivityEventResponseEventType';
import type { RequestActivityPayload } from './requestActivityPayload';

/**
 * Activity event entry associated with a request
 */
export interface RequestActivityEventResponse {
  /** Activity event identifier */
  id?: number;
  /** Request identifier */
  requestId?: number;
  /** Domain activity event type */
  eventType?: RequestActivityEventResponseEventType;
  /** User actor identifier when available */
  actorUserId?: number;
  /** Correlation identifier linking related operations */
  correlationId?: string;
  /** Domain-specific typed event payload */
  payload?: RequestActivityPayload;
  /** Timestamp when the activity event was recorded */
  createdAt?: string;
}
