/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Payload data
 */
export type RequestResponsePayload = { [key: string]: unknown };
