/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Supported operators grouped by input data type
 */
export type RequestTypeModelerCapabilitiesResponseOperatorsByType = {[key: string]: string[]};
