/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Inputs } from './inputs';
import type { RequestTypeModelerCapabilitiesResponseOperatorsByType } from './requestTypeModelerCapabilitiesResponseOperatorsByType';
import type { RequestTypeModelerCapabilitiesResponseAssignmentModesItem } from './requestTypeModelerCapabilitiesResponseAssignmentModesItem';
import type { RequestTypeModelerCapabilitiesResponseAvailableEscalationHandlersItem } from './requestTypeModelerCapabilitiesResponseAvailableEscalationHandlersItem';
import type { ReasonCodeOption } from './reasonCodeOption';

/**
 * Modeler capabilities for a request type version
 */
export interface RequestTypeModelerCapabilitiesResponse {
  /** Request type key */
  typeKey?: string;
  /** Resolved immutable request type version */
  version?: number;
  /** Available request/modeler inputs */
  inputs?: Inputs;
  /** Supported operators grouped by input data type */
  operatorsByType?: RequestTypeModelerCapabilitiesResponseOperatorsByType;
  /** Global assignment mode values */
  assignmentModes?: RequestTypeModelerCapabilitiesResponseAssignmentModesItem[];
  /** Backend-supported escalation handlers */
  availableEscalationHandlers?: RequestTypeModelerCapabilitiesResponseAvailableEscalationHandlersItem[];
  /** Configured reason code catalog entries */
  reasonCodeCatalog?: ReasonCodeOption[];
}
