/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RequestActivitySearchCriteriaEventTypesItem } from './requestActivitySearchCriteriaEventTypesItem';

/**
 * Criteria for searching request activity events
 */
export interface RequestActivitySearchCriteria {
  /**
   * Zero-indexed page number
   * @minimum 0
   */
  page?: number;
  /**
   * Number of records per page
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** Optional activity event type filters */
  eventTypes?: RequestActivitySearchCriteriaEventTypesItem[];
  /** Optional lower bound (inclusive) for event timestamp */
  createdAtFrom?: string;
  /** Optional upper bound (inclusive) for event timestamp */
  createdAtTo?: string;
}
