/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Task completion payload
 */
export interface RequestTaskCompletedActivityPayload {
  /** Request task identifier */
  taskId?: number;
  /** Workflow task identifier */
  taskEngineId?: string;
  /** Task display name */
  taskName?: string;
  /** Task assignee */
  assignee?: string;
  /** Task completion action */
  action?: string;
}
