/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Domain activity event type
 */
export type RequestActivityEventResponseEventType = typeof RequestActivityEventResponseEventType[keyof typeof RequestActivityEventResponseEventType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestActivityEventResponseEventType = {
  STATUS_CHANGED: 'STATUS_CHANGED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_COMPLETED: 'TASK_COMPLETED',
} as const;
