/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * User task details for the request workflow
 */
export interface RequestTaskResponse {
  /** Request task identifier */
  id?: number;
  /** Task display name */
  name?: string;
  /** Task status */
  status?: string;
  /** Task assignee */
  assignee?: string;
}
