/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type RequestTypeModelerCapabilitiesResponseAssignmentModesItem = typeof RequestTypeModelerCapabilitiesResponseAssignmentModesItem[keyof typeof RequestTypeModelerCapabilitiesResponseAssignmentModesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestTypeModelerCapabilitiesResponseAssignmentModesItem = {
  CANDIDATE_USERS: 'CANDIDATE_USERS',
  CANDIDATE_GROUPS: 'CANDIDATE_GROUPS',
  DIRECT_ASSIGNEE: 'DIRECT_ASSIGNEE',
  UNASSIGNED: 'UNASSIGNED',
} as const;
