/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Status transition payload
 */
export interface RequestStatusChangedActivityPayload {
  /** Previous request status */
  fromStatus?: string;
  /** Current request status */
  toStatus?: string;
  /** Related request task id when available */
  taskId?: number;
  /** Related workflow process instance id when available */
  processInstanceId?: string;
}
