/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ResendEsignEnvelope409ErrorsItem } from './resendEsignEnvelope409ErrorsItem';

export type ResendEsignEnvelope409 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: ResendEsignEnvelope409ErrorsItem[];
};
