/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ResendEsignSigner409ErrorsItem } from './resendEsignSigner409ErrorsItem';

export type ResendEsignSigner409 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: ResendEsignSigner409ErrorsItem[];
};
