/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Resolved latest active request type version
 */
export interface ResolvedRequestTypeVersion {
  /** Request type key */
  typeKey?: string;
  /** Resolved immutable version */
  version?: number;
  /** Payload handler identifier */
  payloadHandlerId?: string;
  /** Workflow process definition key */
  processDefinitionKey?: string;
}
