/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TenantSearchCriteria } from './tenantSearchCriteria';

export type Search4Params = {
criteria: TenantSearchCriteria;
};
