/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SearchDocumentTemplatesParams = {
/**
 * English or French name prefix match (case-insensitive)
 */
nameBegins?: string;
/**
 * Optional tenant filter. Null returns all templates
 */
tenantId?: number;
/**
 * Zero-indexed page number
 * @minimum 0
 */
page?: number;
/**
 * Number of records per page
 * @minimum 1
 * @maximum 100
 */
size?: number;
};
