/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RequestTypeSearchCriteria } from './requestTypeSearchCriteria';

export type Search2Params = {
criteria: RequestTypeSearchCriteria;
};
