/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserSearchCriteria } from './userSearchCriteria';

export type Search3Params = {
criteria: UserSearchCriteria;
};
