/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SignerInputAuthMethod } from './signerInputAuthMethod';
import type { SignerInputDeliveryMethod } from './signerInputDeliveryMethod';

export interface SignerInput {
  /** Signature anchor key without surrounding slashes */
  anchorKey: string;
  /** Signer full name */
  fullName: string;
  /** Signer email address. Required for remote EMAIL delivery, optional for remote SMS delivery and in-person signing */
  email?: string;
  /** Remote signer access method. Use NONE for in-person flows */
  authMethod: SignerInputAuthMethod;
  /** Access code required when authMethod is PASSCODE */
  passcode?: string;
  /** SMS number required for SMS delivery and SMS authentication. Common US formats are accepted and normalized to E.164 */
  smsNumber?: string;
  /** Delivery channel for remote signers. Defaults to EMAIL when omitted */
  deliveryMethod?: SignerInputDeliveryMethod;
  /** Explicit recipient routing order */
  routingOrder?: number;
}
