/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Remote signer access method. Use NONE for in-person flows
 */
export type SignerInputAuthMethod = typeof SignerInputAuthMethod[keyof typeof SignerInputAuthMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignerInputAuthMethod = {
  NONE: 'NONE',
  PASSCODE: 'PASSCODE',
  SMS: 'SMS',
} as const;
