/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Delivery channel for remote signers. Defaults to EMAIL when omitted
 */
export type SignerInputDeliveryMethod = typeof SignerInputDeliveryMethod[keyof typeof SignerInputDeliveryMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignerInputDeliveryMethod = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
} as const;
