/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SubmitDraft400ErrorsItem } from './submitDraft400ErrorsItem';

export type SubmitDraft400 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: SubmitDraft400ErrorsItem[];
};
