/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Criteria for searching tenants
 */
export interface TenantSearchCriteria {
  /**
   * Zero-indexed page number
   * @minimum 0
   */
  page?: number;
  /**
   * Number of records per page
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** Case-insensitive tenant name filter */
  nameContains?: string;
  /** Filter by active flag */
  active?: boolean;
  namePattern?: string;
}
