/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Detailed tenant response
 */
export interface TenantResponse {
  /** Tenant identifier */
  id?: number;
  /** Unique tenant name */
  name?: string;
  /** Whether tenant is active */
  active?: boolean;
  /** Creation timestamp */
  createdAt?: string;
  /** Last update timestamp */
  updatedAt?: string;
  /** Optimistic lock version */
  version?: number;
}
