/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DocumentTemplateUpdateRequest } from './documentTemplateUpdateRequest';

export type UpdateDocumentTemplateBody = {
  file?: Blob;
  request: DocumentTemplateUpdateRequest;
};
