/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Update tenant request
 */
export interface UpdateTenantRequest {
  name: string;
  active?: boolean;
  version: number;
}
