/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Update400ErrorsItem } from './update400ErrorsItem';

export type Update400 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: Update400ErrorsItem[];
};
