/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateDraftRequestPayload } from './updateDraftRequestPayload';

/**
 * Request payload for updating an existing draft request
 */
export interface UpdateDraftRequest {
  /** Request payload */
  payload: UpdateDraftRequestPayload;
  /** Current version of the record for optimistic locking */
  version: number;
}
