/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateDraft400ErrorsItem } from './updateDraft400ErrorsItem';

export type UpdateDraft400 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: UpdateDraft400ErrorsItem[];
};
