/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateDocumentTemplate400ErrorsItem } from './updateDocumentTemplate400ErrorsItem';

export type UpdateDocumentTemplate400 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: UpdateDocumentTemplate400ErrorsItem[];
};
