/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Update user request
 */
export interface UpdateUserRequest {
  email: string;
  active?: boolean;
  tenantId?: number;
  version: number;
}
