/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DocumentTemplateUploadRequest } from './documentTemplateUploadRequest';

export type UploadDocumentTemplateBody = {
  file: Blob;
  request: DocumentTemplateUploadRequest;
};
