/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UploadDocumentTemplate400ErrorsItem } from './uploadDocumentTemplate400ErrorsItem';

export type UploadDocumentTemplate400 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: UploadDocumentTemplate400ErrorsItem[];
};
