/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Criteria for searching users
 */
export interface UserSearchCriteria {
  /**
   * Zero-indexed page number
   * @minimum 0
   */
  page?: number;
  /**
   * Number of records per page
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** Case-insensitive username filter */
  usernameContains?: string;
  /** Case-insensitive email filter */
  emailContains?: string;
  /** Filter by active flag */
  active?: boolean;
  /** Filter by tenant identifier */
  tenantId?: number;
  usernamePattern?: string;
  emailPattern?: string;
}
