/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Detailed user response
 */
export interface UserResponse {
  /** User identifier */
  id?: number;
  /** Unique username */
  username?: string;
  /** Unique email */
  email?: string;
  /** Whether the user is active */
  active?: boolean;
  /** Optional tenant identifier */
  tenantId?: number;
  /** Creation timestamp */
  createdAt?: string;
  /** Last update timestamp */
  updatedAt?: string;
  /** Optimistic lock version */
  version?: number;
}
