/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { VoidEsignEnvelope400ErrorsItem } from './voidEsignEnvelope400ErrorsItem';

export type VoidEsignEnvelope400 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: VoidEsignEnvelope400ErrorsItem[];
};
