/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { VoidEsignEnvelope409ErrorsItem } from './voidEsignEnvelope409ErrorsItem';

export type VoidEsignEnvelope409 = {
  type?: string;
  title?: string;
  status?: unknown;
  detail?: string;
  instance?: string;
  errors?: VoidEsignEnvelope409ErrorsItem[];
};
