/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Workflow process-definition search criteria
 */
export interface WorkflowSearchCriteria {
  /**
   * Zero-indexed page number
   * @minimum 0
   */
  page?: number;
  /**
   * Number of records per page
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** Case-insensitive substring filter for process key */
  processDefinitionKeyContains?: string;
  processDefinitionKeyPattern?: string;
}
