/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Deployed workflow process definition
 */
export interface WorkflowDefinitionResponse {
  /** Process definition id */
  id?: string;
  /** Process definition key */
  key?: string;
  /** Process definition name */
  name?: string;
  /** Version */
  version?: number;
}
