CREATE TABLE esign_envelopes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  external_envelope_id VARCHAR(128) NOT NULL UNIQUE,
  provider VARCHAR(32) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  message TEXT,
  delivery_mode VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  tenant_id INTEGER,
  source_file_name VARCHAR(255) NOT NULL,
  source_mime_type VARCHAR(255) NOT NULL,
  source_content_size BIGINT NOT NULL,
  source_checksum_sha256 VARCHAR(64) NOT NULL,
  source_storage_provider VARCHAR(32) NOT NULL,
  source_storage_path TEXT NOT NULL UNIQUE,
  signed_file_name VARCHAR(255),
  signed_mime_type VARCHAR(255),
  signed_content_size BIGINT,
  signed_checksum_sha256 VARCHAR(64),
  signed_storage_provider VARCHAR(32),
  signed_storage_path TEXT UNIQUE,
  certificate_file_name VARCHAR(255),
  certificate_mime_type VARCHAR(255),
  certificate_content_size BIGINT,
  certificate_checksum_sha256 VARCHAR(64),
  certificate_storage_provider VARCHAR(32),
  certificate_storage_path TEXT UNIQUE,
  reminders_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  reminder_interval_hours INTEGER,
  voided_reason TEXT,
  completed_at TIMESTAMPTZ,
  last_provider_update_at TIMESTAMPTZ,
  created_by INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_by INTEGER NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_esign_envelopes_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_esign_envelopes_updated_by FOREIGN KEY (updated_by) REFERENCES users(id),
  CONSTRAINT fk_esign_envelopes_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE esign_signers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  envelope_id BIGINT NOT NULL,
  role_key VARCHAR(32) NOT NULL,
  signature_anchor_text VARCHAR(32) NOT NULL,
  date_anchor_text VARCHAR(32),
  routing_order INTEGER NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone_number VARCHAR(50),
  auth_method VARCHAR(32) NOT NULL,
  sms_number VARCHAR(50),
  provider_recipient_id VARCHAR(64),
  status VARCHAR(32) NOT NULL,
  viewed_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  last_status_at TIMESTAMPTZ,
  created_by INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_by INTEGER NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_esign_signers_envelope_id FOREIGN KEY (envelope_id) REFERENCES esign_envelopes(id),
  CONSTRAINT fk_esign_signers_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_esign_signers_updated_by FOREIGN KEY (updated_by) REFERENCES users(id),
  CONSTRAINT uk_esign_signers_envelope_role UNIQUE (envelope_id, role_key)
);

CREATE INDEX idx_esign_envelopes_status ON esign_envelopes(status);
CREATE INDEX idx_esign_envelopes_tenant_id ON esign_envelopes(tenant_id);
CREATE INDEX idx_esign_signers_envelope_id ON esign_signers(envelope_id);
CREATE INDEX idx_esign_signers_status ON esign_signers(status);
